'use strict'
const { test } = require('node:test')
const assert = require('node:assert/strict')
const { load, save, normalize, FIELDS } = require('../src/client/motion-settings')
test('saved old defaults upgrade once while custom values survive', t => {
  const original = global.localStorage
  let stored = JSON.stringify({ stepThreshold: 0.13, swingThreshold: 2.5, phoneThreshold: 3, lookSpeed: 1.7 })
  global.localStorage = { getItem: () => stored, setItem: (key, value) => { stored = value } }
  t.after(() => { if (original === undefined) delete global.localStorage; else global.localStorage = original })
  const settings = load()
  assert.equal(settings.stepThreshold, 0.08)
  assert.equal(settings.swingThreshold, 3.5)
  assert.equal(settings.phoneThreshold, 0.1)
  assert.equal(settings.lookSpeed, 1.7)
  save({ ...settings, stepThreshold: 0.13 })
  assert.equal(load().stepThreshold, 0.13, 'An intentional adjustment is not migrated again')
  stored = JSON.stringify({ defaultsVersion: 2, phoneThreshold: 2, stepThreshold: 0.13 })
  assert.equal(load().phoneThreshold, 0.1)
  assert.equal(load().stepThreshold, 0.13)
  stored = JSON.stringify({ defaultsVersion: 3, phoneThreshold: 1.2 })
  assert.equal(load().phoneThreshold, 0.1)
  save({ ...load(), phoneThreshold: 0.1 })
  assert.equal(load().phoneThreshold, 0.1, 'Low thresholds are not clamped back to the old minimum')
  save({ ...load(), phoneThreshold: 2 })
  assert.equal(load().phoneThreshold, 2, 'Intentional threshold changes survive subsequent loads')
  stored = JSON.stringify({ stepThreshold: 0.2, swingThreshold: 4, phoneThreshold: 1.5 })
  const custom = load()
  assert.equal(custom.stepThreshold, 0.2)
  assert.equal(custom.swingThreshold, 4)
  assert.equal(custom.phoneThreshold, 1.5)
})

test('camera choice persists as a facing mode or a device id', () => {
  assert.equal(normalize({}).camera, 'user')
  assert.equal(normalize({ camera: 'environment' }).camera, 'environment')
  assert.equal(normalize({ camera: 'a1b2c3' }).camera, 'a1b2c3')
  assert.equal(normalize({ camera: '' }).camera, 'user')
  assert.equal(normalize({ camera: 42 }).camera, 'user')
  assert.equal(normalize({ camera: 'x'.repeat(129) }).camera, 'user')
})

test('phone threshold slider and saved settings stay within 0.1 to 2 m/s²', () => {
  assert.equal(FIELDS.phoneThreshold[1], 0.1)
  assert.equal(FIELDS.phoneThreshold[2], 2)
  assert.equal(normalize({ phoneThreshold: 8 }).phoneThreshold, 2)
  assert.equal(normalize({ phoneThreshold: 0 }).phoneThreshold, 0.1)
})
